//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETradingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int wallet_Id { get; set; }
        public Nullable<decimal> Customer_Id { get; set; }
        public Nullable<System.DateTime> Date_of_Top_Up { get; set; }
        public Nullable<double> Last_Top_Up { get; set; }
        public Nullable<double> Total_Top_Up { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
