//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETrading.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public decimal Admin_Id { get; set; }
        public string Admin_Email { get; set; }
        public string Admin_Name { get; set; }
        public string Password { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
    }
}
